version: "3"
services:
  db:
    image: "postgres:11"
    container_name: "cajetan"
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - cajetan:/var/lib/postgresql/data
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
volumes:
  cajetan: