INSERT INTO team (moniker, location, league) VALUES ('Cardinals',       'Arizona',        'NFL');
INSERT INTO team (moniker, location, league) VALUES ('Falcons',         'Atlanta',        'NFL');
INSERT INTO team (moniker, location, league) VALUES ('Ravens',          'Baltimore',      'NFL');
INSERT INTO team (moniker, location, league) VALUES ('Bills',           'Buffalo',        'NFL');
INSERT INTO team (moniker, location, league) VALUES ('Panthers',        'Carolina',       'NFL');
INSERT INTO team (moniker, location, league) VALUES ('Bears',           'Chicago',        'NFL');
INSERT INTO team (moniker, location, league) VALUES ('Bengals',         'Cincinnati',     'NFL');
INSERT INTO team (moniker, location, league) VALUES ('Browns',          'Cleveland',      'NFL');
INSERT INTO team (moniker, location, league) VALUES ('Cowboys',         'Dallas',         'NFL');
INSERT INTO team (moniker, location, league) VALUES ('Broncos',         'Denver',         'NFL');
INSERT INTO team (moniker, location, league) VALUES ('Lions',           'Detroit',        'NFL');
INSERT INTO team (moniker, location, league) VALUES ('Packers',         'Green Bay',      'NFL');
INSERT INTO team (moniker, location, league) VALUES ('Texans',          'Houston',        'NFL');
INSERT INTO team (moniker, location, league) VALUES ('Colts',           'Indianapolis',   'NFL');
INSERT INTO team (moniker, location, league) VALUES ('Jaguars',         'Jacksonville',   'NFL');
INSERT INTO team (moniker, location, league) VALUES ('Chiefs',          'Kansas City',    'NFL');
INSERT INTO team (moniker, location, league) VALUES ('Raiders',         'Las Vegas',      'NFL');
INSERT INTO team (moniker, location, league) VALUES ('Chargers',        'Los Angeles',    'NFL');
INSERT INTO team (moniker, location, league) VALUES ('Rams',            'Los Angeles',    'NFL');
INSERT INTO team (moniker, location, league) VALUES ('Dolphins',        'Miami',          'NFL');
INSERT INTO team (moniker, location, league) VALUES ('Vikings',         'Minnesota',      'NFL');
INSERT INTO team (moniker, location, league) VALUES ('Patriots',        'New England',    'NFL');
INSERT INTO team (moniker, location, league) VALUES ('Saints',          'New Orleans',    'NFL');
INSERT INTO team (moniker, location, league) VALUES ('Giants',          'New York',       'NFL');
INSERT INTO team (moniker, location, league) VALUES ('Jets',            'New York',       'NFL');
INSERT INTO team (moniker, location, league) VALUES ('Eagles',          'Philadelphia',   'NFL');
INSERT INTO team (moniker, location, league) VALUES ('Steelers',        'Pittsburgh',     'NFL');
INSERT INTO team (moniker, location, league) VALUES ('49ers',           'San Francisco',  'NFL');
INSERT INTO team (moniker, location, league) VALUES ('Seahawks',        'Seattle',        'NFL');
INSERT INTO team (moniker, location, league) VALUES ('Buccaneers',      'Tampa Bay',      'NFL');
INSERT INTO team (moniker, location, league) VALUES ('Titans',          'Tennessee',      'NFL');
INSERT INTO team (moniker, location, league) VALUES ('Redskins',        'Washington',     'NFL');

INSERT INTO team (moniker, location, league) VALUES ('Hawks',           'Atlanta',        'NBA');
INSERT INTO team (moniker, location, league) VALUES ('Celtics',         'Boston',         'NBA');
INSERT INTO team (moniker, location, league) VALUES ('Nets',            'Brooklyn',       'NBA');
INSERT INTO team (moniker, location, league) VALUES ('Hornets',         'Charlotte',      'NBA');
INSERT INTO team (moniker, location, league) VALUES ('Bulls',           'Chicago',        'NBA');
INSERT INTO team (moniker, location, league) VALUES ('Cavaliers',       'Cleveland',      'NBA');
INSERT INTO team (moniker, location, league) VALUES ('Mavericks',       'Dallas',         'NBA');
INSERT INTO team (moniker, location, league) VALUES ('Nuggets',         'Denver',         'NBA');
INSERT INTO team (moniker, location, league) VALUES ('Pistons',         'Detroit',        'NBA');
INSERT INTO team (moniker, location, league) VALUES ('Warriors',        'Golden State',   'NBA');
INSERT INTO team (moniker, location, league) VALUES ('Rockets',         'Houston',        'NBA');
INSERT INTO team (moniker, location, league) VALUES ('Pacers',          'Indiana',        'NBA');
INSERT INTO team (moniker, location, league) VALUES ('Clippers',        'Los Angeles',    'NBA');
INSERT INTO team (moniker, location, league) VALUES ('Lakers',          'Los Angeles',    'NBA');
INSERT INTO team (moniker, location, league) VALUES ('Grizzlies',       'Memphis',        'NBA');
INSERT INTO team (moniker, location, league) VALUES ('Heat',            'Miami',          'NBA');
INSERT INTO team (moniker, location, league) VALUES ('Bucks',           'Milwaukee',      'NBA');
INSERT INTO team (moniker, location, league) VALUES ('Timberwolves',    'Minnesota',      'NBA');
INSERT INTO team (moniker, location, league) VALUES ('Pelicans',        'New Orleans',    'NBA');
INSERT INTO team (moniker, location, league) VALUES ('Knicks',          'New York',       'NBA');
INSERT INTO team (moniker, location, league) VALUES ('Thunder',         'Oklahoma City',  'NBA');
INSERT INTO team (moniker, location, league) VALUES ('Magic',           'Orlando',        'NBA');
INSERT INTO team (moniker, location, league) VALUES ('76ers',           'Philadelphia',   'NBA');
INSERT INTO team (moniker, location, league) VALUES ('Suns',            'Phoenix',        'NBA');
INSERT INTO team (moniker, location, league) VALUES ('Trailblazers',    'Portland',       'NBA');
INSERT INTO team (moniker, location, league) VALUES ('Kings',           'Sacramento',     'NBA');
INSERT INTO team (moniker, location, league) VALUES ('Spurs',           'San Antonio',    'NBA');
INSERT INTO team (moniker, location, league) VALUES ('Raptors',         'Toronto',        'NBA');
INSERT INTO team (moniker, location, league) VALUES ('Jazz',            'Utah',           'NBA');
INSERT INTO team (moniker, location, league) VALUES ('Wizards',         'Washington',     'NBA');

INSERT INTO team (moniker, location, league) VALUES ('Diamondbacks',    'Arizona',        'MLB');
INSERT INTO team (moniker, location, league) VALUES ('Braves',          'Atlanta',        'MLB');
INSERT INTO team (moniker, location, league) VALUES ('Orioles',         'Baltimore',      'MLB');
INSERT INTO team (moniker, location, league) VALUES ('Red Sox',         'Boston',         'MLB');
INSERT INTO team (moniker, location, league) VALUES ('Cubs',            'Chicago',        'MLB');
INSERT INTO team (moniker, location, league) VALUES ('White Sox',       'Chicago',        'MLB');
INSERT INTO team (moniker, location, league) VALUES ('Reds',            'Cincinnati',     'MLB');
INSERT INTO team (moniker, location, league) VALUES ('Indians',         'Cleveland',      'MLB');
INSERT INTO team (moniker, location, league) VALUES ('Rockies',         'Colorado',       'MLB');
INSERT INTO team (moniker, location, league) VALUES ('Tigers',          'Detroit',        'MLB');
INSERT INTO team (moniker, location, league) VALUES ('Astros',          'Houston',        'MLB');
INSERT INTO team (moniker, location, league) VALUES ('Royals',          'Kansas City',    'MLB');
INSERT INTO team (moniker, location, league) VALUES ('Angels',          'Los Angeles',    'MLB');
INSERT INTO team (moniker, location, league) VALUES ('Dodgers',         'Los Angeles',    'MLB');
INSERT INTO team (moniker, location, league) VALUES ('Marlins',         'Miami',          'MLB');
INSERT INTO team (moniker, location, league) VALUES ('Brewers',         'Milwaukee',      'MLB');
INSERT INTO team (moniker, location, league) VALUES ('Twins',           'Minnesota',      'MLB');
INSERT INTO team (moniker, location, league) VALUES ('Mets',            'New York',       'MLB');
INSERT INTO team (moniker, location, league) VALUES ('Yankees',         'New York',       'MLB');
INSERT INTO team (moniker, location, league) VALUES ('Athletics',       'Oakland',        'MLB');
INSERT INTO team (moniker, location, league) VALUES ('Phillies',        'Philadelphia',   'MLB');
INSERT INTO team (moniker, location, league) VALUES ('Pirates',         'Pittsburgh',     'MLB');
INSERT INTO team (moniker, location, league) VALUES ('Padres',          'San Diego',      'MLB');
INSERT INTO team (moniker, location, league) VALUES ('Giants',          'San Francisco',  'MLB');
INSERT INTO team (moniker, location, league) VALUES ('Mariners',        'Seattle',        'MLB');
INSERT INTO team (moniker, location, league) VALUES ('Cardinals',       'St. Louis',      'MLB');
INSERT INTO team (moniker, location, league) VALUES ('Devil Rays',      'Tampa Bay',      'MLB');
INSERT INTO team (moniker, location, league) VALUES ('Rangers',         'Texas',          'MLB');
INSERT INTO team (moniker, location, league) VALUES ('Blue Jays',       'Toronto',        'MLB');
INSERT INTO team (moniker, location, league) VALUES ('Nationals',       'Washington',     'MLB');

INSERT INTO team (moniker, location, league) VALUES ('Ducks',           'Anaheim',        'NHL');
INSERT INTO team (moniker, location, league) VALUES ('Coyotes',         'Arizona',        'NHL');
INSERT INTO team (moniker, location, league) VALUES ('Bruins',          'Boston',         'NHL');
INSERT INTO team (moniker, location, league) VALUES ('Sabres',          'Buffalo',        'NHL');
INSERT INTO team (moniker, location, league) VALUES ('Flames',          'Calgary',        'NHL');
INSERT INTO team (moniker, location, league) VALUES ('Hurricans',       'Carolina',       'NHL');
INSERT INTO team (moniker, location, league) VALUES ('Blackhawks',      'Chicago',        'NHL');
INSERT INTO team (moniker, location, league) VALUES ('Avalanche',       'Colorado',       'NHL');
INSERT INTO team (moniker, location, league) VALUES ('Blue Jackets',    'Columbus',       'NHL');
INSERT INTO team (moniker, location, league) VALUES ('Stars',           'Dallas',         'NHL');
INSERT INTO team (moniker, location, league) VALUES ('Red Wings',       'Detroit',        'NHL');
INSERT INTO team (moniker, location, league) VALUES ('Oilers',          'Edmonton',       'NHL');
INSERT INTO team (moniker, location, league) VALUES ('Panthers',        'Florida',        'NHL');
INSERT INTO team (moniker, location, league) VALUES ('Golden Knights',  'Las Vegas',      'NHL');
INSERT INTO team (moniker, location, league) VALUES ('Kings',           'Los Angeles',    'NHL');
INSERT INTO team (moniker, location, league) VALUES ('Wild',            'Minnesota',      'NHL');
INSERT INTO team (moniker, location, league) VALUES ('Canadiens',       'Montreal',       'NHL');
INSERT INTO team (moniker, location, league) VALUES ('Predators',       'Nashville',      'NHL');
INSERT INTO team (moniker, location, league) VALUES ('Devils',          'New Jersey',     'NHL');
INSERT INTO team (moniker, location, league) VALUES ('Islanders',       'New York',       'NHL');
INSERT INTO team (moniker, location, league) VALUES ('Rangers',         'New York',       'NHL');
INSERT INTO team (moniker, location, league) VALUES ('Senators',        'Ottawa',         'NHL');
INSERT INTO team (moniker, location, league) VALUES ('Flyers',          'Philadelphia',   'NHL');
INSERT INTO team (moniker, location, league) VALUES ('Penguins',        'Pittsburgh',     'NHL');
INSERT INTO team (moniker, location, league) VALUES ('Blues',           'St. Louis',      'NHL');
INSERT INTO team (moniker, location, league) VALUES ('Sharks',          'San Jose',       'NHL');
INSERT INTO team (moniker, location, league) VALUES ('Lightning',       'Tampa Bay',      'NHL');
INSERT INTO team (moniker, location, league) VALUES ('Maple Leafs',     'Toronto',        'NHL');
INSERT INTO team (moniker, location, league) VALUES ('Canucks',         'Vancouver',      'NHL');
INSERT INTO team (moniker, location, league) VALUES ('Capitals',        'Washington',     'NHL');
INSERT INTO team (moniker, location, league) VALUES ('Jets',            'Winnipeg',       'NHL');

INSERT INTO team_search_term (team_id, term) SELECT id, 'SFO'             FROM team WHERE moniker = '49ers'           AND league = 'NFL' LIMIT 1;
INSERT INTO team_search_term (team_id, term) SELECT id, 'SF'              FROM team WHERE moniker = '49ers'           AND league = 'NFL' LIMIT 1;
INSERT INTO team_search_term (team_id, term) SELECT id, 'CHI'             FROM team WHERE moniker = 'Bears'           AND league = 'NFL' LIMIT 1;
INSERT INTO team_search_term (team_id, term) SELECT id, 'CIN'             FROM team WHERE moniker = 'Bengals'         AND league = 'NFL' LIMIT 1;
INSERT INTO team_search_term (team_id, term) SELECT id, 'BUF'             FROM team WHERE moniker = 'Bills'           AND league = 'NFL' LIMIT 1;
INSERT INTO team_search_term (team_id, term) SELECT id, 'DEN'             FROM team WHERE moniker = 'Broncos'         AND league = 'NFL' LIMIT 1;
INSERT INTO team_search_term (team_id, term) SELECT id, 'CLE'             FROM team WHERE moniker = 'Browns'          AND league = 'NFL' LIMIT 1;
INSERT INTO team_search_term (team_id, term) SELECT id, 'TAM'             FROM team WHERE moniker = 'Buccaneers'      AND league = 'NFL' LIMIT 1;
INSERT INTO team_search_term (team_id, term) SELECT id, 'TB'              FROM team WHERE moniker = 'Buccaneers'      AND league = 'NFL' LIMIT 1;
INSERT INTO team_search_term (team_id, term) SELECT id, 'ARI'             FROM team WHERE moniker = 'Cardinals'       AND league = 'NFL' LIMIT 1;
INSERT INTO team_search_term (team_id, term) SELECT id, 'LAC'             FROM team WHERE moniker = 'Chargers'        AND league = 'NFL' LIMIT 1;
INSERT INTO team_search_term (team_id, term) SELECT id, 'SDG'             FROM team WHERE moniker = 'Chargers'        AND league = 'NFL' LIMIT 1;
INSERT INTO team_search_term (team_id, term) SELECT id, 'KAN'             FROM team WHERE moniker = 'Chiefs'          AND league = 'NFL' LIMIT 1;
INSERT INTO team_search_term (team_id, term) SELECT id, 'KC'              FROM team WHERE moniker = 'Chiefs'          AND league = 'NFL' LIMIT 1;
INSERT INTO team_search_term (team_id, term) SELECT id, 'IND'             FROM team WHERE moniker = 'Colts'           AND league = 'NFL' LIMIT 1;
INSERT INTO team_search_term (team_id, term) SELECT id, 'DAL'             FROM team WHERE moniker = 'Cowboys'         AND league = 'NFL' LIMIT 1;
INSERT INTO team_search_term (team_id, term) SELECT id, 'MIA'             FROM team WHERE moniker = 'Dolphins'        AND league = 'NFL' LIMIT 1;
INSERT INTO team_search_term (team_id, term) SELECT id, 'PHI'             FROM team WHERE moniker = 'Eagles'          AND league = 'NFL' LIMIT 1;
INSERT INTO team_search_term (team_id, term) SELECT id, 'ATL'             FROM team WHERE moniker = 'Falcons'         AND league = 'NFL' LIMIT 1;
INSERT INTO team_search_term (team_id, term) SELECT id, 'NYG'             FROM team WHERE moniker = 'Giants'          AND league = 'NFL' LIMIT 1;
INSERT INTO team_search_term (team_id, term) SELECT id, 'JAX'             FROM team WHERE moniker = 'Jaguars'         AND league = 'NFL' LIMIT 1;
INSERT INTO team_search_term (team_id, term) SELECT id, 'JAC'             FROM team WHERE moniker = 'Jaguars'         AND league = 'NFL' LIMIT 1;
INSERT INTO team_search_term (team_id, term) SELECT id, 'NYJ'             FROM team WHERE moniker = 'Jets'            AND league = 'NFL' LIMIT 1;
INSERT INTO team_search_term (team_id, term) SELECT id, 'DET'             FROM team WHERE moniker = 'Lions'           AND league = 'NFL' LIMIT 1;
INSERT INTO team_search_term (team_id, term) SELECT id, 'GB'              FROM team WHERE moniker = 'Packers'         AND league = 'NFL' LIMIT 1;
INSERT INTO team_search_term (team_id, term) SELECT id, 'GNB'             FROM team WHERE moniker = 'Packers'         AND league = 'NFL' LIMIT 1;
INSERT INTO team_search_term (team_id, term) SELECT id, 'CAR'             FROM team WHERE moniker = 'Panthers'        AND league = 'NFL' LIMIT 1;
INSERT INTO team_search_term (team_id, term) SELECT id, 'NE'              FROM team WHERE moniker = 'Patriots'        AND league = 'NFL' LIMIT 1;
INSERT INTO team_search_term (team_id, term) SELECT id, 'NWE'             FROM team WHERE moniker = 'Patriots'        AND league = 'NFL' LIMIT 1;
INSERT INTO team_search_term (team_id, term) SELECT id, 'OAK'             FROM team WHERE moniker = 'Raiders'         AND league = 'NFL' LIMIT 1;
INSERT INTO team_search_term (team_id, term) SELECT id, 'STL'             FROM team WHERE moniker = 'Rams'            AND league = 'NFL' LIMIT 1;
INSERT INTO team_search_term (team_id, term) SELECT id, 'LA'              FROM team WHERE moniker = 'Rams'            AND league = 'NFL' LIMIT 1;
INSERT INTO team_search_term (team_id, term) SELECT id, 'LAR'             FROM team WHERE moniker = 'Rams'            AND league = 'NFL' LIMIT 1;
INSERT INTO team_search_term (team_id, term) SELECT id, 'BAL'             FROM team WHERE moniker = 'Ravens'          AND league = 'NFL' LIMIT 1;
INSERT INTO team_search_term (team_id, term) SELECT id, 'WSH'             FROM team WHERE moniker = 'Redskins'        AND league = 'NFL' LIMIT 1;
INSERT INTO team_search_term (team_id, term) SELECT id, 'WAS'             FROM team WHERE moniker = 'Redskins'        AND league = 'NFL' LIMIT 1;
INSERT INTO team_search_term (team_id, term) SELECT id, 'NOR'             FROM team WHERE moniker = 'Saints'          AND league = 'NFL' LIMIT 1;
INSERT INTO team_search_term (team_id, term) SELECT id, 'NO'              FROM team WHERE moniker = 'Saints'          AND league = 'NFL' LIMIT 1;
INSERT INTO team_search_term (team_id, term) SELECT id, 'SEA'             FROM team WHERE moniker = 'Seahawks'        AND league = 'NFL' LIMIT 1;
INSERT INTO team_search_term (team_id, term) SELECT id, 'PIT'             FROM team WHERE moniker = 'Steelers'        AND league = 'NFL' LIMIT 1;
INSERT INTO team_search_term (team_id, term) SELECT id, 'HOU'             FROM team WHERE moniker = 'Texans'          AND league = 'NFL' LIMIT 1;
INSERT INTO team_search_term (team_id, term) SELECT id, 'TEN'             FROM team WHERE moniker = 'Titans'          AND league = 'NFL' LIMIT 1;
INSERT INTO team_search_term (team_id, term) SELECT id, 'MIN'             FROM team WHERE moniker = 'Vikings'         AND league = 'NFL' LIMIT 1;

INSERT INTO team_search_term (team_id, term) SELECT id, 'ATL'             FROM team WHERE moniker = 'Hawks'           AND league = 'NBA' LIMIT 1;
INSERT INTO team_search_term (team_id, term) SELECT id, 'BOS'             FROM team WHERE moniker = 'Celtics'         AND league = 'NBA' LIMIT 1;
INSERT INTO team_search_term (team_id, term) SELECT id, 'BKN'             FROM team WHERE moniker = 'Nets'            AND league = 'NBA' LIMIT 1;
INSERT INTO team_search_term (team_id, term) SELECT id, 'CHA'             FROM team WHERE moniker = 'Hornets'         AND league = 'NBA' LIMIT 1;
INSERT INTO team_search_term (team_id, term) SELECT id, 'CHI'             FROM team WHERE moniker = 'Bulls'           AND league = 'NBA' LIMIT 1;
INSERT INTO team_search_term (team_id, term) SELECT id, 'CLE'             FROM team WHERE moniker = 'Cavaliers'       AND league = 'NBA' LIMIT 1;
INSERT INTO team_search_term (team_id, term) SELECT id, 'DAL'             FROM team WHERE moniker = 'Mavericks'       AND league = 'NBA' LIMIT 1;
INSERT INTO team_search_term (team_id, term) SELECT id, 'DEN'             FROM team WHERE moniker = 'Nuggets'         AND league = 'NBA' LIMIT 1;
INSERT INTO team_search_term (team_id, term) SELECT id, 'DET'             FROM team WHERE moniker = 'Pistons'         AND league = 'NBA' LIMIT 1;
INSERT INTO team_search_term (team_id, term) SELECT id, 'GSW'             FROM team WHERE moniker = 'Warriors'        AND league = 'NBA' LIMIT 1;
INSERT INTO team_search_term (team_id, term) SELECT id, 'HOU'             FROM team WHERE moniker = 'Rockets'         AND league = 'NBA' LIMIT 1;
INSERT INTO team_search_term (team_id, term) SELECT id, 'IND'             FROM team WHERE moniker = 'Pacers'          AND league = 'NBA' LIMIT 1;
INSERT INTO team_search_term (team_id, term) SELECT id, 'LAC'             FROM team WHERE moniker = 'Clippers'        AND league = 'NBA' LIMIT 1;
INSERT INTO team_search_term (team_id, term) SELECT id, 'LAL'             FROM team WHERE moniker = 'Lakers'          AND league = 'NBA' LIMIT 1;
INSERT INTO team_search_term (team_id, term) SELECT id, 'MEM'             FROM team WHERE moniker = 'Grizzlies'       AND league = 'NBA' LIMIT 1;
INSERT INTO team_search_term (team_id, term) SELECT id, 'MIA'             FROM team WHERE moniker = 'Heat'            AND league = 'NBA' LIMIT 1;
INSERT INTO team_search_term (team_id, term) SELECT id, 'MIL'             FROM team WHERE moniker = 'Bucks'           AND league = 'NBA' LIMIT 1;
INSERT INTO team_search_term (team_id, term) SELECT id, 'MIN'             FROM team WHERE moniker = 'Timberwolves'    AND league = 'NBA' LIMIT 1;
INSERT INTO team_search_term (team_id, term) SELECT id, 'NOR'             FROM team WHERE moniker = 'Pelicans'        AND league = 'NBA' LIMIT 1;
INSERT INTO team_search_term (team_id, term) SELECT id, 'NYK'             FROM team WHERE moniker = 'Knicks'          AND league = 'NBA' LIMIT 1;
INSERT INTO team_search_term (team_id, term) SELECT id, 'OKC'             FROM team WHERE moniker = 'Thunder'         AND league = 'NBA' LIMIT 1;
INSERT INTO team_search_term (team_id, term) SELECT id, 'ORL'             FROM team WHERE moniker = 'Magic'           AND league = 'NBA' LIMIT 1;
INSERT INTO team_search_term (team_id, term) SELECT id, 'PHI'             FROM team WHERE moniker = '76ers'           AND league = 'NBA' LIMIT 1;
INSERT INTO team_search_term (team_id, term) SELECT id, 'PHO'             FROM team WHERE moniker = 'Suns'            AND league = 'NBA' LIMIT 1;
INSERT INTO team_search_term (team_id, term) SELECT id, 'POR'             FROM team WHERE moniker = 'Trailblazers'    AND league = 'NBA' LIMIT 1;
INSERT INTO team_search_term (team_id, term) SELECT id, 'SAC'             FROM team WHERE moniker = 'Kings'           AND league = 'NBA' LIMIT 1;
INSERT INTO team_search_term (team_id, term) SELECT id, 'SAS'             FROM team WHERE moniker = 'Spurs'           AND league = 'NBA' LIMIT 1;
INSERT INTO team_search_term (team_id, term) SELECT id, 'TOR'             FROM team WHERE moniker = 'Raptors'         AND league = 'NBA' LIMIT 1;
INSERT INTO team_search_term (team_id, term) SELECT id, 'UTH'             FROM team WHERE moniker = 'Jazz'            AND league = 'NBA' LIMIT 1;
INSERT INTO team_search_term (team_id, term) SELECT id, 'WAS'             FROM team WHERE moniker = 'Wizards'         AND league = 'NBA' LIMIT 1;

INSERT INTO team_search_term (team_id, term) SELECT id, 'Arizona'         FROM team WHERE moniker = 'Diamondbacks'    AND league = 'MLB' LIMIT 1;
INSERT INTO team_search_term (team_id, term) SELECT id, 'Atlanta'         FROM team WHERE moniker = 'Braves'          AND league = 'MLB' LIMIT 1;
INSERT INTO team_search_term (team_id, term) SELECT id, 'Baltimore'       FROM team WHERE moniker = 'Orioles'         AND league = 'MLB' LIMIT 1;
INSERT INTO team_search_term (team_id, term) SELECT id, 'Boston'          FROM team WHERE moniker = 'Red Sox'         AND league = 'MLB' LIMIT 1;
INSERT INTO team_search_term (team_id, term) SELECT id, 'Chi. Cubs'       FROM team WHERE moniker = 'Cubs'            AND league = 'MLB' LIMIT 1;
INSERT INTO team_search_term (team_id, term) SELECT id, 'Chi. White Sox'  FROM team WHERE moniker = 'White Sox'       AND league = 'MLB' LIMIT 1;
INSERT INTO team_search_term (team_id, term) SELECT id, 'Cincinnati'      FROM team WHERE moniker = 'Reds'            AND league = 'MLB' LIMIT 1;
INSERT INTO team_search_term (team_id, term) SELECT id, 'Cleveland'       FROM team WHERE moniker = 'Indians'         AND league = 'MLB' LIMIT 1;
INSERT INTO team_search_term (team_id, term) SELECT id, 'Colorado'        FROM team WHERE moniker = 'Rockies'         AND league = 'MLB' LIMIT 1;
INSERT INTO team_search_term (team_id, term) SELECT id, 'Detroit'         FROM team WHERE moniker = 'Tigers'          AND league = 'MLB' LIMIT 1;
INSERT INTO team_search_term (team_id, term) SELECT id, 'Houston'         FROM team WHERE moniker = 'Astros'          AND league = 'MLB' LIMIT 1;
INSERT INTO team_search_term (team_id, term) SELECT id, 'Kansas City'     FROM team WHERE moniker = 'Royals'          AND league = 'MLB' LIMIT 1;
INSERT INTO team_search_term (team_id, term) SELECT id, 'L.A. Angels'     FROM team WHERE moniker = 'Angels'          AND league = 'MLB' LIMIT 1;
INSERT INTO team_search_term (team_id, term) SELECT id, 'L.A. Dodgers'    FROM team WHERE moniker = 'Dodgers'         AND league = 'MLB' LIMIT 1;
INSERT INTO team_search_term (team_id, term) SELECT id, 'Miami'           FROM team WHERE moniker = 'Marlins'         AND league = 'MLB' LIMIT 1;
INSERT INTO team_search_term (team_id, term) SELECT id, 'Milwaukee'       FROM team WHERE moniker = 'Brewers'         AND league = 'MLB' LIMIT 1;
INSERT INTO team_search_term (team_id, term) SELECT id, 'Minnesota'       FROM team WHERE moniker = 'Twins'           AND league = 'MLB' LIMIT 1;
INSERT INTO team_search_term (team_id, term) SELECT id, 'N.Y. Mets'       FROM team WHERE moniker = 'Mets'            AND league = 'MLB' LIMIT 1;
INSERT INTO team_search_term (team_id, term) SELECT id, 'N.Y. Yankees'    FROM team WHERE moniker = 'Yankees'         AND league = 'MLB' LIMIT 1;
INSERT INTO team_search_term (team_id, term) SELECT id, 'Oakland'         FROM team WHERE moniker = 'Athletics'       AND league = 'MLB' LIMIT 1;
INSERT INTO team_search_term (team_id, term) SELECT id, 'Philadelphia'    FROM team WHERE moniker = 'Phillies'        AND league = 'MLB' LIMIT 1;
INSERT INTO team_search_term (team_id, term) SELECT id, 'Pittsburgh'      FROM team WHERE moniker = 'Pirates'         AND league = 'MLB' LIMIT 1;
INSERT INTO team_search_term (team_id, term) SELECT id, 'San Diego'       FROM team WHERE moniker = 'Padres'          AND league = 'MLB' LIMIT 1;
INSERT INTO team_search_term (team_id, term) SELECT id, 'San Francisco'   FROM team WHERE moniker = 'Giants'          AND league = 'MLB' LIMIT 1;
INSERT INTO team_search_term (team_id, term) SELECT id, 'Seattle'         FROM team WHERE moniker = 'Mariners'        AND league = 'MLB' LIMIT 1;
INSERT INTO team_search_term (team_id, term) SELECT id, 'St. Louis'       FROM team WHERE moniker = 'Cardinals'       AND league = 'MLB' LIMIT 1;
INSERT INTO team_search_term (team_id, term) SELECT id, 'Tampa Bay'       FROM team WHERE moniker = 'Devil Rays'      AND league = 'MLB' LIMIT 1;
INSERT INTO team_search_term (team_id, term) SELECT id, 'Texas'           FROM team WHERE moniker = 'Rangers'         AND league = 'MLB' LIMIT 1;
INSERT INTO team_search_term (team_id, term) SELECT id, 'Toronto'         FROM team WHERE moniker = 'Blue Jays'       AND league = 'MLB' LIMIT 1;
INSERT INTO team_search_term (team_id, term) SELECT id, 'Washington'      FROM team WHERE moniker = 'Nationals'       AND league = 'MLB' LIMIT 1;

INSERT INTO team_search_term (team_id, term) SELECT id, 'ANA'             FROM team WHERE moniker = 'Ducks'           AND league = 'NHL' LIMIT 1;
INSERT INTO team_search_term (team_id, term) SELECT id, 'ARI'             FROM team WHERE moniker = 'Coyotes'         AND league = 'NHL' LIMIT 1;
INSERT INTO team_search_term (team_id, term) SELECT id, 'BOS'             FROM team WHERE moniker = 'Bruins'          AND league = 'NHL' LIMIT 1;
INSERT INTO team_search_term (team_id, term) SELECT id, 'BUF'             FROM team WHERE moniker = 'Sabres'          AND league = 'NHL' LIMIT 1;
INSERT INTO team_search_term (team_id, term) SELECT id, 'CGY'             FROM team WHERE moniker = 'Flames'          AND league = 'NHL' LIMIT 1;
INSERT INTO team_search_term (team_id, term) SELECT id, 'CAR'             FROM team WHERE moniker = 'Hurricans'       AND league = 'NHL' LIMIT 1;
INSERT INTO team_search_term (team_id, term) SELECT id, 'CHI'             FROM team WHERE moniker = 'Blackhawks'      AND league = 'NHL' LIMIT 1;
INSERT INTO team_search_term (team_id, term) SELECT id, 'COL'             FROM team WHERE moniker = 'Avalanche'       AND league = 'NHL' LIMIT 1;
INSERT INTO team_search_term (team_id, term) SELECT id, 'COB'             FROM team WHERE moniker = 'Blue Jackets'    AND league = 'NHL' LIMIT 1;
INSERT INTO team_search_term (team_id, term) SELECT id, 'DAL'             FROM team WHERE moniker = 'Stars'           AND league = 'NHL' LIMIT 1;
INSERT INTO team_search_term (team_id, term) SELECT id, 'DET'             FROM team WHERE moniker = 'Red Wings'       AND league = 'NHL' LIMIT 1;
INSERT INTO team_search_term (team_id, term) SELECT id, 'EDM'             FROM team WHERE moniker = 'Oilers'          AND league = 'NHL' LIMIT 1;
INSERT INTO team_search_term (team_id, term) SELECT id, 'FLA'             FROM team WHERE moniker = 'Panthers'        AND league = 'NHL' LIMIT 1;
INSERT INTO team_search_term (team_id, term) SELECT id, 'VGK'             FROM team WHERE moniker = 'Golden Knights'  AND league = 'NHL' LIMIT 1;
INSERT INTO team_search_term (team_id, term) SELECT id, 'LOS'             FROM team WHERE moniker = 'Kings'           AND league = 'NHL' LIMIT 1;
INSERT INTO team_search_term (team_id, term) SELECT id, 'MIN'             FROM team WHERE moniker = 'Wild'            AND league = 'NHL' LIMIT 1;
INSERT INTO team_search_term (team_id, term) SELECT id, 'MON'             FROM team WHERE moniker = 'Canadiens'       AND league = 'NHL' LIMIT 1;
INSERT INTO team_search_term (team_id, term) SELECT id, 'NAS'             FROM team WHERE moniker = 'Predators'       AND league = 'NHL' LIMIT 1;
INSERT INTO team_search_term (team_id, term) SELECT id, 'NJD'             FROM team WHERE moniker = 'Devils'          AND league = 'NHL' LIMIT 1;
INSERT INTO team_search_term (team_id, term) SELECT id, 'NYI'             FROM team WHERE moniker = 'Islanders'       AND league = 'NHL' LIMIT 1;
INSERT INTO team_search_term (team_id, term) SELECT id, 'NYR'             FROM team WHERE moniker = 'Rangers'         AND league = 'NHL' LIMIT 1;
INSERT INTO team_search_term (team_id, term) SELECT id, 'OTT'             FROM team WHERE moniker = 'Senators'        AND league = 'NHL' LIMIT 1;
INSERT INTO team_search_term (team_id, term) SELECT id, 'PHI'             FROM team WHERE moniker = 'Flyers'          AND league = 'NHL' LIMIT 1;
INSERT INTO team_search_term (team_id, term) SELECT id, 'PIT'             FROM team WHERE moniker = 'Penguins'        AND league = 'NHL' LIMIT 1;
INSERT INTO team_search_term (team_id, term) SELECT id, 'STL'             FROM team WHERE moniker = 'Blues'           AND league = 'NHL' LIMIT 1;
INSERT INTO team_search_term (team_id, term) SELECT id, 'SAN'             FROM team WHERE moniker = 'Sharks'          AND league = 'NHL' LIMIT 1;
INSERT INTO team_search_term (team_id, term) SELECT id, 'TAM'             FROM team WHERE moniker = 'Lightning'       AND league = 'NHL' LIMIT 1;
INSERT INTO team_search_term (team_id, term) SELECT id, 'TOR'             FROM team WHERE moniker = 'Maple Leafs'     AND league = 'NHL' LIMIT 1;
INSERT INTO team_search_term (team_id, term) SELECT id, 'VAN'             FROM team WHERE moniker = 'Canucks'         AND league = 'NHL' LIMIT 1;
INSERT INTO team_search_term (team_id, term) SELECT id, 'WAS'             FROM team WHERE moniker = 'Capitals'        AND league = 'NHL' LIMIT 1;
INSERT INTO team_search_term (team_id, term) SELECT id, 'WIN'             FROM team WHERE moniker = 'Jets'            AND league = 'NHL' LIMIT 1;